language: julia
os:
  - linux
julia:
  - nightly
  - 1.0

service_name: travis-pro
repo_token: LcuAfIQSUa8QskwO7PcbdgitCdiVjHUXi
  
script:
- julia -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'

after_success:
- julia -e 'cd(Pkg.dir("TravisTest")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'