language: julia
os:
  - linux
julia:
  - nightly
  - 1.0
  
script:
- julia -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'

after_success:
 - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
#- julia -e 'cd(Pkg.dir("TravisTest")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'